name: weixin-article-save
description: 'Get the WeChat public account article and save it as a jpg picture'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'download-cloud'  
  color: 'white'
